name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      TF_VAR_sql_admin_username: ${{ secrets.TF_VAR_sql_admin_username }}
      TF_VAR_sql_admin_password: ${{ secrets.TF_VAR_sql_admin_password }}
      TF_VAR_azure_subscription_id: ${{ secrets.TF_VAR_azure_subscription_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform  
        uses: hashicorp/setup-terraform@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init  
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  apply:
    needs: plan
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      TF_VAR_sql_admin_username: ${{ secrets.TF_VAR_sql_admin_username }}
      TF_VAR_sql_admin_password: ${{ secrets.TF_VAR_sql_admin_password }}
      TF_VAR_azure_subscription_id: ${{ secrets.TF_VAR_azure_subscription_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan