name: Terraform Test

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TF_VAR_sql_admin_username: ${{ secrets.TF_VAR_sql_admin_username }}
      TF_VAR_sql_admin_password: ${{ secrets.TF_VAR_sql_admin_password }}
      TF_VAR_azure_subscription_id: ${{ secrets.TF_VAR_azure_subscription_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate